#-----Установка zabbix-server
# ---
- hosts: zabbixserver
  become: yes
  gather_facts: true
#--------Переменные--------
  vars:   
    mysql_password: 123456
#--------------------------
  tasks:
#--------Загрузка дистрибутива zabbix и установка--------
    - name: Загрузка deb пакета zabbix 
      ansible.builtin.apt:
          deb: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb"
    - name: Установка (nginx, mysql-server, zabbix-server-mysql, zabbix-frontend-php, zabbix-nginx-conf, zabbix-sql-scripts, zabbix-agent)
      ansible.builtin.apt:
        update_cache: true
        name: nginx, mysql-server, zabbix-server-mysql, zabbix-frontend-php, zabbix-nginx-conf, zabbix-sql-scripts, zabbix-agent, python3-pip 
        state: present 
#--------Копируем конфигурационные файлы--------
    - name: Скопируем "zabbix_server.conf" на место, создав копию оригинала
      ansible.builtin.copy:
          src: /home/pavel/diplom/zabbix_server.conf
          dest: /etc/zabbix/zabbix_server.conf
          owner: root
          group: root
          mode: '0644'
          backup: yes
    - name: Скопируем "nginx.conf" на место, создав копию оригинала
      ansible.builtin.copy:
          src: /home/pavel/diplom/nginx.conf
          dest: /etc/zabbix/nginx.conf
          owner: root
          group: root
          mode: '0644'
          backup: yes  
 #--------Создание базы MySql, пользователя и загрузка данных Zabbix--------  
    - name: Install MySQL
      pip:
        name: mysql
        state: present 
    - name: создаем базу
      community.mysql.mysql_db:
          login_host: zabbixserver
          name: zabbix
          state: present
          login_unix_socket: /run/mysqld/mysqld.sock 
    - name: создаем пользователя   
      community.mysql.mysql_user:
          login_host: zabbixserver
          name: zabbix
          password: "{{mysql_password}}"
          priv: '*.*:ALL,GRANT'
          state: present 
          login_unix_socket: /run/mysqld/mysqld.sock 
    - name: Выполните следующие комманды на хосте, где будет распологаться база данных. zabbix.
      community.mysql.mysql_query:
         login_host: zabbixserver
         login_db: zabbix
         query: 
         - grant all privileges on zabbix.* to zabbix@localhost
         - set global log_bin_trust_function_creators = 1
         login_unix_socket: /run/mysqld/mysqld.sock   
    - name: на хосте Zabbix сервера импортируйте начальную схему и данные
      community.mysql.mysql_db: 
         name: zabbix 
         state: import 
         target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz 
         login_unix_socket: /run/mysqld/mysqld.sock
    - name: Выключите опцию log_bin_trust_function_creators после импорта схемы базы данных.
      community.mysql.mysql_query:
         login_db: zabbix
         query: set global log_bin_trust_function_creators = 0
         login_unix_socket: /run/mysqld/mysqld.sock 

#--------Перезагружаем службы--------         
    - name: Перезагружаем службы 
      ansible.builtin.systemd:
          name: "{{ item }}"
          enabled: yes
          state: restarted 
      with_items:
          - zabbix-server
          - zabbix-agent 
          - nginx
          - php7.4-fpm 
    - name: Скопируем "zabbix.conf.php" 
      ansible.builtin.copy:
          src: /home/pavel/diplom/zabbix.conf.php
          dest: /etc/zabbix/web/zabbix.conf.php
          owner: root
          group: root
          mode: '0644'    
